#!/usr/bin/env python3
"""Generate public-facing pages for the next Steinmetz source expansion wave.

This layer does not pretend unacquired works have been decoded. It turns the
bibliography/intake frontier into reader value: essential-paper routes, concept
impact maps, acquisition gates, and source-wave dashboards.
"""

from __future__ import annotations

import html
import json
import re
from collections import defaultdict
from datetime import date
from pathlib import Path
from typing import Any

BASE_URL = ""
GENERATED_NOTE = "{/* Generated by pipeline/scripts/generate_source_expansion_wave.py. Do not edit by hand. */}"
BEGIN = "{/* BEGIN GENERATED SOURCE WAVE IMPACT */}"
END = "{/* END GENERATED SOURCE WAVE IMPACT */}"

CORE_CONCEPT_SLUGS = {
    "ether",
    "hysteresis",
    "complex-quantities",
    "symbolic-method",
    "impedance",
    "reactance",
    "admittance",
    "transient-phenomena",
    "lightning-surges",
    "distributed-constants",
    "electric-waves",
    "dielectric-loss",
    "inductance-capacity",
}

WAVE_TARGETS: dict[str, dict[str, Any]] = {
    "law-of-hysteresis-1892": {
        "wave": "Hysteresis And Symbolic Method Spine",
        "rank": 1,
        "concepts": ["hysteresis", "magnetic-fields", "dielectric-loss", "inductance-capacity"],
        "reader_title": "Hysteresis law and magnetic loss",
        "reader_value": "This is the origin point for Steinmetz's magnetic-loss reputation. It should eventually anchor the hysteresis concept page, the Steinmetz equation page, and modern core-loss comparison.",
        "gate": "Acquire primary scan or publisher PDF, then transcribe equations and any magnetic-loss curves against page images.",
    },
    "complex-quantities-use-electrical-engineering-1894": {
        "wave": "Hysteresis And Symbolic Method Spine",
        "rank": 2,
        "concepts": ["complex-quantities", "symbolic-method", "impedance", "reactance", "admittance"],
        "reader_title": "Complex quantities and the birth of engineering phasors",
        "reader_value": "This should become the flagship source for how Steinmetz made alternating-current calculation algebraic, geometric, and teachable.",
        "gate": "Verify against the International Electrical Congress proceedings scan before promoting any quotation or equation.",
    },
    "general-equations-electric-circuit-1908": {
        "wave": "Hysteresis And Symbolic Method Spine",
        "rank": 3,
        "concepts": ["symbolic-method", "complex-quantities", "transient-phenomena", "impedance", "distributed-constants"],
        "reader_title": "General equations of the electric circuit",
        "reader_value": "This paper bridges steady-state symbolic method, differential equations, and the general circuit theory behind later source books.",
        "gate": "Acquire article text and preserve equation/page mapping before adding formulas to the curated math canon.",
    },
    "general-equations-electric-circuit-iii-1919": {
        "wave": "Hysteresis And Symbolic Method Spine",
        "rank": 4,
        "concepts": ["symbolic-method", "transient-phenomena", "distributed-constants", "impedance"],
        "reader_title": "General circuit equations, continuation",
        "reader_value": "The continuation lets the archive show development over time rather than treating general circuit equations as a one-off article.",
        "gate": "Acquire together with the 1908 paper so the series can be decoded as a sequence.",
    },
    "mechanical-forces-magnetic-fields-1910": {
        "wave": "Hysteresis And Symbolic Method Spine",
        "rank": 5,
        "concepts": ["magnetic-fields", "hysteresis", "ether", "inductance-capacity"],
        "reader_title": "Mechanical forces, magnetic stress, and field language",
        "reader_value": "This is the highest-value pending source for force, stress, pressure, and tension vocabulary in magnetic fields.",
        "gate": "Acquire the article and separate explicit Steinmetz field-force language from later ether-field interpretation.",
    },
    "lightning-phenomena-electric-circuits-1907": {
        "wave": "Transients, Lightning, Distributed Constants, And Surge Spine",
        "rank": 6,
        "concepts": ["lightning-surges", "transient-phenomena", "electric-waves", "distributed-constants"],
        "reader_title": "Lightning phenomena in electric circuits",
        "reader_value": "This should become a cornerstone for surge theory, steep wave fronts, impulse behavior, and high-voltage protection.",
        "gate": "Acquire the proceedings scan and extract impulse-wave diagrams only after page-image verification.",
    },
    "natural-period-transmission-line-lightning-1898": {
        "wave": "Transients, Lightning, Distributed Constants, And Surge Spine",
        "rank": 7,
        "concepts": ["distributed-constants", "lightning-surges", "electric-waves", "transient-phenomena"],
        "reader_title": "Natural period of transmission lines and lightning discharge",
        "reader_value": "This is the missing early bridge between line constants, natural oscillation, and lightning-frequency reasoning.",
        "gate": "Locate the Electrical World issue or a library scan before any source text is generated.",
    },
    "disruptive-strength-transient-voltages-1910": {
        "wave": "Transients, Lightning, Distributed Constants, And Surge Spine",
        "rank": 8,
        "concepts": ["lightning-surges", "dielectric-loss", "transient-phenomena"],
        "reader_title": "Disruptive strength under transient voltage",
        "reader_value": "This source should strengthen insulation stress, breakdown, and surge-dielectric language.",
        "gate": "Acquire primary scan and keep Hayden/Steinmetz authorship visible in citations.",
    },
    "instability-electric-circuits-1914": {
        "wave": "Transients, Lightning, Distributed Constants, And Surge Spine",
        "rank": 9,
        "concepts": ["transient-phenomena", "oscillation-damping", "lightning-surges"],
        "reader_title": "Instability of electric circuits",
        "reader_value": "This source can connect cumulative circuit behavior, negative-resistance-like effects, oscillation, and protective design.",
        "gate": "Acquire article scan and route suspicious OCR formulas into review, not curated math.",
    },
    "outline-theory-impulse-currents-1916": {
        "wave": "Transients, Lightning, Distributed Constants, And Surge Spine",
        "rank": 10,
        "concepts": ["lightning-surges", "transient-phenomena", "distributed-constants"],
        "reader_title": "Theory of impulse currents",
        "reader_value": "This is a direct mathematical source for impulse-current reasoning and should feed the surge math route.",
        "gate": "Acquire article and scan-check each equation before adding to canonical formula pages.",
    },
    "oxide-film-lightning-arrester-1918": {
        "wave": "Transients, Lightning, Distributed Constants, And Surge Spine",
        "rank": 11,
        "concepts": ["lightning-surges", "dielectric-loss", "electric-apparatus"],
        "reader_title": "Oxide film lightning arrester",
        "reader_value": "This source turns surge theory into protective apparatus and belongs beside the patent-to-theory bridge.",
        "gate": "Acquire scan and keep apparatus claims separate from general transient theory.",
    },
    "condenser-discharges-general-gas-circuit-1922": {
        "wave": "Transients, Lightning, Distributed Constants, And Surge Spine",
        "rank": 12,
        "concepts": ["transient-phenomena", "oscillation-damping", "dielectric-loss"],
        "reader_title": "Condenser discharges through a gas circuit",
        "reader_value": "This should enrich discharge, damping, oscillation, and nonlinear gas-circuit behavior.",
        "gate": "Acquire article and verify whether figures or oscillograms exist before visual promotion.",
    },
    "cable-charge-and-discharge-1923": {
        "wave": "Transients, Lightning, Distributed Constants, And Surge Spine",
        "rank": 13,
        "concepts": ["distributed-constants", "transient-phenomena", "inductance-capacity", "electric-waves"],
        "reader_title": "Cable charge, discharge, and distributed capacity",
        "reader_value": "This is the direct source for cable transients and should strengthen the line/capacity side of the archive.",
        "gate": "Acquire article and page-map charge/discharge curves before diagram promotion.",
    },
    "frequency-conversion-third-class-conductor-arcing-ground-1923": {
        "wave": "Transients, Lightning, Distributed Constants, And Surge Spine",
        "rank": 14,
        "concepts": ["lightning-surges", "transient-phenomena", "oscillation-damping", "electric-waves"],
        "reader_title": "Arcing grounds and cumulative surges",
        "reader_value": "This is a flagship pending source for nonlinear discharge, arcing-ground behavior, frequency conversion, and cumulative surges.",
        "gate": "Acquire scan and separate source equations, apparatus behavior, and later interpretive synthesis.",
    },
    "future-of-electricity-1910": {
        "wave": "Context, Bibliography, And Archival Expansion",
        "rank": 15,
        "concepts": ["historical-context", "power-systems", "social-electricity"],
        "reader_title": "The future of electricity",
        "reader_value": "This short work should help readers understand Steinmetz's civilizational view of electrification without confusing it with circuit theory.",
        "gate": "Acquire public scan or HathiTrust-accessible page images before OCR.",
    },
    "systems-electric-transmission-distribution-1900": {
        "wave": "Context, Bibliography, And Archival Expansion",
        "rank": 16,
        "concepts": ["power-systems", "alternating-current", "distributed-constants"],
        "reader_title": "Systems of electric transmission and distribution",
        "reader_value": "This should connect Steinmetz's high theory to practical power-system layout and AC distribution choices.",
        "gate": "Verify public text availability and edition identity before processing.",
    },
    "steinmetz-patents-corpus": {
        "wave": "Context, Bibliography, And Archival Expansion",
        "rank": 17,
        "concepts": ["electric-apparatus", "lightning-surges", "illumination", "hysteresis", "inductance-capacity"],
        "reader_title": "Patent-to-theory bridge",
        "reader_value": "The patent corpus is the practical apparatus counterpart to the books and papers. It needs claims, drawings, and concept links, not just a list of patent numbers.",
        "gate": "Normalize the full authority corpus before claiming completeness; the current bridge is seeded examples only.",
    },
}

CONCEPT_SOURCE_WAVE: dict[str, dict[str, Any]] = {
    "hysteresis": {
        "headline": "The next corpus wave should make hysteresis far more source-complete.",
        "works": ["law-of-hysteresis-1892", "mechanical-forces-magnetic-fields-1910", "theory-general-alternating-current-transformer-1895"],
        "note": "Until the 1892 paper is in custody, the page should keep using already processed books and lectures while marking the original law paper as the highest acquisition target.",
    },
    "complex-quantities": {
        "headline": "The missing flagship is Steinmetz's 1893/1894 complex-quantities paper.",
        "works": ["complex-quantities-use-electrical-engineering-1894", "general-equations-electric-circuit-1908", "general-equations-electric-circuit-iii-1919"],
        "note": "The current page is grounded in processed textbooks; the proceedings paper will become the primary origin-point once scanned and sectioned.",
    },
    "symbolic-method": {
        "headline": "The symbolic method needs its paper trail, not only later textbook treatment.",
        "works": ["complex-quantities-use-electrical-engineering-1894", "general-equations-electric-circuit-1908", "general-equations-electric-circuit-iii-1919"],
        "note": "Keep the 1897/1900/1916 AC editions visible as the book-development layer while the paper sources remain acquisition targets.",
    },
    "impedance": {
        "headline": "Impedance will be strengthened by the complex-quantity and general-equation sources.",
        "works": ["complex-quantities-use-electrical-engineering-1894", "general-equations-electric-circuit-1908", "general-equations-electric-circuit-iii-1919"],
        "note": "The current reader route remains the AC book editions and Electric Circuits; papers should not be cited as decoded until acquired.",
    },
    "reactance": {
        "headline": "Reactance sits at the center of the next AC-method expansion.",
        "works": ["complex-quantities-use-electrical-engineering-1894", "general-equations-electric-circuit-1908", "systems-electric-transmission-distribution-1900"],
        "note": "Watch for how Steinmetz separates resistance, reactance, and stored-field exchange across editions and papers.",
    },
    "admittance": {
        "headline": "Admittance should be connected back to the broader symbolic-method wave.",
        "works": ["complex-quantities-use-electrical-engineering-1894", "general-equations-electric-circuit-1908"],
        "note": "Parallel-circuit method is strongest in processed books for now; the new paper wave supplies origin and generalization once acquired.",
    },
    "transient-phenomena": {
        "headline": "The next wave is especially strong for transients.",
        "works": ["lightning-phenomena-electric-circuits-1907", "outline-theory-impulse-currents-1916", "instability-electric-circuits-1914", "condenser-discharges-general-gas-circuit-1922", "frequency-conversion-third-class-conductor-arcing-ground-1923"],
        "note": "Use processed transient books now; pending articles will sharpen impulse, instability, gas discharge, and cumulative-surge layers.",
    },
    "lightning-surges": {
        "headline": "Lightning and surge theory is the most urgent article-acquisition cluster.",
        "works": ["natural-period-transmission-line-lightning-1898", "lightning-phenomena-electric-circuits-1907", "disruptive-strength-transient-voltages-1910", "outline-theory-impulse-currents-1916", "oxide-film-lightning-arrester-1918", "frequency-conversion-third-class-conductor-arcing-ground-1923"],
        "note": "Keep existing surge statements grounded in processed transients until these articles have scan custody and equation review.",
    },
    "distributed-constants": {
        "headline": "Distributed constants gain a much stronger line-and-cable route in the next wave.",
        "works": ["natural-period-transmission-line-lightning-1898", "cable-charge-and-discharge-1923", "systems-electric-transmission-distribution-1900"],
        "note": "This should connect line theory, natural period, cable charge/discharge, and practical transmission systems.",
    },
    "electric-waves": {
        "headline": "Electric waves should be expanded through line, lightning, and cable sources.",
        "works": ["natural-period-transmission-line-lightning-1898", "lightning-phenomena-electric-circuits-1907", "cable-charge-and-discharge-1923"],
        "note": "The current wave/radiation pages already help; the new sources will make circuit waves and line waves more precise.",
    },
    "dielectric-loss": {
        "headline": "Dielectric and insulation language gets a stronger high-voltage path.",
        "works": ["disruptive-strength-transient-voltages-1910", "condenser-discharges-general-gas-circuit-1922", "cable-charge-and-discharge-1923"],
        "note": "Treat breakdown and gas discharge as source-specific phenomena rather than generic dielectric mystique.",
    },
    "inductance-capacity": {
        "headline": "Inductance and capacity connect directly to cable, line, and discharge sources.",
        "works": ["cable-charge-and-discharge-1923", "natural-period-transmission-line-lightning-1898", "condenser-discharges-general-gas-circuit-1922"],
        "note": "This is a good reader doorway into distributed rather than lumped electrical behavior.",
    },
    "ether": {
        "headline": "Ether remains a boundary topic, not a claim bucket.",
        "works": ["mechanical-forces-magnetic-fields-1910", "complex-quantities-use-electrical-engineering-1894", "future-of-electricity-1910"],
        "note": "The new sources may enrich field-language context, but Wheeler-style or broader ether-field readings must remain labeled interpretation unless Steinmetz explicitly says it.",
    },
}


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def esc(value: Any) -> str:
    return html.escape("" if value is None else str(value), quote=True)


def md(value: Any) -> str:
    return ("" if value is None else str(value)).replace("|", "\\|")


def normalize_records(matrix: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {str(record.get("work_id")): record for record in matrix.get("records", []) if record.get("work_id")}


def wave_records(matrix: dict[str, Any]) -> list[dict[str, Any]]:
    records = normalize_records(matrix)
    out = []
    for work_id, insight in WAVE_TARGETS.items():
        record = dict(records.get(work_id, {}))
        record.setdefault("work_id", work_id)
        record.update(insight)
        record["title"] = record.get("title") or insight["reader_title"]
        record["coverage_state"] = record.get("coverage_state") or "planned-acquisition"
        record["links"] = record.get("links") or {}
        out.append(record)
    return sorted(out, key=lambda item: int(item.get("rank", 999)))


def page_link(record: dict[str, Any]) -> str:
    source_text = (record.get("links") or {}).get("source_text")
    if source_text:
        return str(source_text)
    return f"{BASE_URL}/source-library/corpus-completion/works/{record['work_id']}/"


def source_state_label(record: dict[str, Any]) -> str:
    state = str(record.get("coverage_state") or "planned-acquisition")
    return state.replace("-", " ").title()


def concept_links(record: dict[str, Any]) -> str:
    links = []
    for slug in record.get("concepts", []):
        if slug in CORE_CONCEPT_SLUGS:
            links.append(f'<a href="/concepts/{esc(slug)}/">{esc(slug.replace("-", " ").title())}</a>')
        else:
            links.append(f'<span>{esc(slug.replace("-", " ").title())}</span>')
    return " ".join(links)


def target_card(record: dict[str, Any]) -> str:
    authority = f'<a href="{esc(record.get("authority_url"))}">Authority</a>' if record.get("authority_url") else '<span>Authority/custody pending</span>'
    return f"""<article class="source-wave-card" data-state="{esc(record.get('coverage_state'))}">
  <span class="source-wave-rank">#{esc(record.get('rank'))}</span>
  <h3><a href="{esc(page_link(record))}">{esc(record.get('title'))}</a></h3>
  <p class="source-wave-meta">{esc(record.get('year') or 'undated')} - {esc(record.get('source_type') or 'source target')} - {esc(source_state_label(record))}</p>
  <p>{esc(record.get('reader_value'))}</p>
  <p><strong>Gate:</strong> {esc(record.get('gate'))}</p>
  <div class="source-wave-links"><a href="{esc(page_link(record))}">Record</a>{authority}</div>
  <div class="source-wave-concepts">{concept_links(record)}</div>
</article>"""


def build_wave_page(records: list[dict[str, Any]]) -> str:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for record in records:
        grouped[record["wave"]].append(record)
    sections = []
    for wave, items in grouped.items():
        cards = "\n".join(target_card(item) for item in items)
        sections.append(f"## {wave}\n\n<div class=\"source-wave-grid\">\n{cards}\n</div>")
    rows = "\n".join(
        f'<tr><td><a href="{esc(page_link(record))}">{esc(record.get("reader_title"))}</a></td><td>{esc(", ".join(record.get("concepts", [])))}</td><td>{esc(record.get("gate"))}</td></tr>'
        for record in records
    )
    return f"""---
title: Steinmetz Source Expansion Wave
description: The next serious acquisition and processing wave for Steinmetz Decoded.
---

{GENERATED_NOTE}

This is the public map for the next large expansion of Steinmetz Decoded. It separates three things that must never be mixed: works already in the processed corpus, works registered by authority trail, and works still awaiting public scan or file custody.

The archive will not cite an unprocessed paper as decoded. But the reader deserves to see why these sources matter, what concepts they will strengthen, and what has to happen before each one becomes source text, math, diagrams, glossary, hidden gems, and searchable evidence.

<div class="source-text-warning" data-layer="source">
  <strong>Source boundary:</strong> registered authority is not decoded evidence. These records become full source pages only after custody, OCR/text extraction, page or section mapping, candidate catalogs, and review labels are visible.
</div>

<div class="reader-door-grid">
  <a href="/essential-steinmetz-papers/"><strong>Read The Essential Papers Map</strong><span>Five source priorities that explain why the next wave matters.</span></a>
  <a href="/source-library/corpus-completion/critical-frontier/"><strong>Open Critical Frontier</strong><span>The no-shortcuts list of unprocessed critical works.</span></a>
  <a href="/concepts/complex-quantities/"><strong>Follow AC Method</strong><span>Complex quantities, symbolic method, impedance, and reactance.</span></a>
  <a href="/concepts/lightning-surges/"><strong>Follow Surge Theory</strong><span>Lightning, line waves, impulse currents, arresters, and cumulative surges.</span></a>
</div>

{chr(10).join(sections)}

## How These Sources Will Enrich The Site

<table class="codex-status-table source-wave-table">
  <thead><tr><th>Work</th><th>Concept Pages Affected</th><th>Public Gate</th></tr></thead>
  <tbody>
{rows}
  </tbody>
</table>
"""


def build_essential_page(records: list[dict[str, Any]]) -> str:
    pick_ids = [
        "law-of-hysteresis-1892",
        "complex-quantities-use-electrical-engineering-1894",
        "general-equations-electric-circuit-1908",
        "mechanical-forces-magnetic-fields-1910",
        "lightning-phenomena-electric-circuits-1907",
        "cable-charge-and-discharge-1923",
        "frequency-conversion-third-class-conductor-arcing-ground-1923",
    ]
    by_id = {record["work_id"]: record for record in records}
    cards = "\n".join(target_card(by_id[work_id]) for work_id in pick_ids if work_id in by_id)
    return f"""---
title: Essential Steinmetz Papers
description: The highest-value Steinmetz papers and short works to acquire, decode, and read first.
---

{GENERATED_NOTE}

Steinmetz Decoded already has a broad book corpus. The next jump in quality comes from the papers where his most famous ideas first appeared or became technically sharp. This page is for readers who want to know what the archive is chasing next and why it matters.

<div class="source-text-warning" data-layer="source">
  <strong>Reading rule:</strong> if a paper is not yet in source custody, use this page as a guide to the acquisition frontier, not as a substitute for Steinmetz's text.
</div>

<div class="source-wave-grid essential-paper-grid">
{cards}
</div>

## What To Read Right Now

While these papers are being acquired and verified, use the already processed corpus:

- [Complex Quantities](/concepts/complex-quantities/) and [Symbolic Method](/concepts/symbolic-method/) for the AC calculation route.
- [Hysteresis](/concepts/hysteresis/) and [Steinmetz Hysteresis Law](/mathematics/equations/steinmetz-hysteresis-law/) for magnetic loss.
- [Transient Phenomena](/concepts/transient-phenomena/), [Lightning And Surges](/concepts/lightning-surges/), and [Distributed Constants](/concepts/distributed-constants/) for surge and line behavior.
- [Electric Discharges, Waves and Impulses, 1914](/book-coverage/electric-discharges-waves-impulses-1914/) for the strongest processed transient source.
- [Theory and Calculation of Electric Circuits](/book-coverage/theory-calculation-electric-circuits/) for the broadest processed circuit source.
"""


def build_newly_added_page(matrix: dict[str, Any]) -> str:
    records = [record for record in matrix.get("records", []) if record.get("coverage_state") in {"processed-corpus", "ocr-seeded-corpus"}]
    records.sort(key=lambda item: (0 if item.get("coverage_state") == "ocr-seeded-corpus" else 1, str(item.get("title"))))
    rows = []
    for record in records:
        links = record.get("links") or {}
        open_link = links.get("source_text") or links.get("coverage") or links.get("source") or f"/source-library/corpus-completion/works/{record.get('work_id')}/"
        rows.append(f'<tr><td><a href="{esc(open_link)}">{esc(record.get("title"))}</a></td><td>{esc(record.get("year") or "")}</td><td>{esc(source_state_label(record))}</td><td>{esc(record.get("why_it_matters") or "Processed source record.")}</td></tr>')
    return f"""---
title: Newly Added Steinmetz Works
description: Recently seeded and processed Steinmetz sources now participating in the public archive.
---

{GENERATED_NOTE}

These works already have generated public surfaces: source records, reader routes where available, book coverage, candidate math, concept signals, glossary signals, visual routes, or research workbenches. OCR-seeded does not mean scan-reviewed; it means the source is inside the repeatable processing system.

<table class="codex-status-table source-wave-table">
  <thead><tr><th>Source</th><th>Year</th><th>State</th><th>Why It Matters</th></tr></thead>
  <tbody>
{chr(10).join(rows)}
  </tbody>
</table>

## Next Reader Move

If you are here to learn rather than audit the archive, open [Start Reading](/start-reading/), [Concept Encyclopedia](/concepts/), or [Essential Steinmetz Papers](/essential-steinmetz-papers/).
"""


def build_math_map_page(records: list[dict[str, Any]]) -> str:
    math_groups = [
        ("Hysteresis And Magnetic Loss", ["law-of-hysteresis-1892", "mechanical-forces-magnetic-fields-1910"], ["/concepts/hysteresis/", "/mathematics/equations/steinmetz-hysteresis-law/"]),
        ("Complex AC And Symbolic Method", ["complex-quantities-use-electrical-engineering-1894", "general-equations-electric-circuit-1908", "general-equations-electric-circuit-iii-1919"], ["/concepts/complex-quantities/", "/concepts/symbolic-method/", "/mathematics/equation-atlas/symbolic-ac/"]),
        ("Transients, Lines, And Surges", ["natural-period-transmission-line-lightning-1898", "lightning-phenomena-electric-circuits-1907", "outline-theory-impulse-currents-1916", "cable-charge-and-discharge-1923"], ["/concepts/transient-phenomena/", "/concepts/distributed-constants/", "/concepts/lightning-surges/"]),
        ("Nonlinear Discharge And Cumulative Surges", ["instability-electric-circuits-1914", "condenser-discharges-general-gas-circuit-1922", "frequency-conversion-third-class-conductor-arcing-ground-1923"], ["/concepts/oscillation-damping/", "/concepts/lightning-surges/"]),
    ]
    by_id = {record["work_id"]: record for record in records}
    sections = []
    for title, ids, routes in math_groups:
        work_links = ", ".join(f'[{md(by_id[i].get("reader_title"))}]({page_link(by_id[i])})' for i in ids if i in by_id)
        route_links = " | ".join(f"[route]({route})" for route in routes)
        sections.append(f"### {title}\n\n- **Pending source spine:** {work_links}.\n- **Read now:** {route_links}.\n- **Trust rule:** source-reader OCR math remains unrendered until equations are manually verified against scans.\n")
    return f"""---
title: Steinmetz Math Map
description: A reader-first map of Steinmetz mathematical topics, processed routes, and pending source-wave papers.
---

{GENERATED_NOTE}

This page helps readers find the mathematical core without drowning in raw OCR formula candidates. Curated math pages may use KaTeX. Source-reader OCR formula fragments remain verification items until reviewed.

{chr(10).join(sections)}

## Verification Boundary

A formula can be historically important and still be unverified in the current archive. The correct path is: source custody, page image, OCR candidate, manual transcription, variable definition, modern notation, derivation, and only then canonical equation promotion.
"""


def source_wave_block(slug: str, records: list[dict[str, Any]]) -> str:
    config = CONCEPT_SOURCE_WAVE.get(slug)
    if not config:
        return ""
    by_id = {record["work_id"]: record for record in records}
    rows = []
    for work_id in config["works"]:
        record = by_id.get(work_id)
        if not record:
            continue
        rows.append(f'<tr><td><a href="{esc(page_link(record))}">{esc(record.get("title"))}</a></td><td>{esc(record.get("year") or "")}</td><td>{esc(source_state_label(record))}</td><td>{esc(record.get("reader_value"))}</td></tr>')
    return f"""{BEGIN}

## Source Expansion Impact

<div class="source-wave-impact" data-layer="source">
  <h3>{esc(config['headline'])}</h3>
  <p>{esc(config['note'])}</p>
</div>

<table class="codex-status-table source-wave-table">
  <thead><tr><th>Source Target</th><th>Year</th><th>Status</th><th>Why It Matters Here</th></tr></thead>
  <tbody>
{chr(10).join(rows)}
  </tbody>
</table>

{END}"""


def replace_or_insert(existing: str, block: str) -> str:
    if not block:
        return existing
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
    if pattern.search(existing):
        return pattern.sub(block, existing).rstrip() + "\n"
    marker = "{/* BEGIN GENERATED CONCEPT DOSSIER */}"
    if marker in existing:
        return existing.replace(marker, block + "\n\n" + marker, 1)
    return existing.rstrip() + "\n\n" + block + "\n"


def update_concepts(root: Path, records: list[dict[str, Any]]) -> int:
    docs = root / "site" / "src" / "content" / "docs" / "concepts"
    count = 0
    for slug in CONCEPT_SOURCE_WAVE:
        path = docs / f"{slug}.mdx"
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        new_text = replace_or_insert(text, source_wave_block(slug, records))
        if new_text != text:
            write_text(path, new_text)
            count += 1
    return count


WORK_BEGIN = "{/* BEGIN GENERATED SOURCE WAVE WORK IMPACT */}"
WORK_END = "{/* END GENERATED SOURCE WAVE WORK IMPACT */}"


def work_impact_block(record: dict[str, Any]) -> str:
    concept_html = " ".join(
        f'<a href="/concepts/{esc(slug)}/">{esc(slug.replace("-", " ").title())}</a>'
        if slug in CORE_CONCEPT_SLUGS else f'<span>{esc(slug.replace("-", " ").title())}</span>'
        for slug in record.get("concepts", [])
    )
    authority = f'<a href="{esc(record.get("authority_url"))}">Authority trail</a>' if record.get("authority_url") else '<span>Authority/custody pending</span>'
    return f"""{WORK_BEGIN}

## Reader Value And Concept Impact

<div class="source-wave-impact" data-layer="source">
  <h3>{esc(record.get('reader_title') or record.get('title'))}</h3>
  <p>{esc(record.get('reader_value'))}</p>
  <p><strong>Processing gate:</strong> {esc(record.get('gate'))}</p>
</div>

<div class="source-wave-links">
  <a href="/source-library/steinmetz-source-expansion-wave/">Source expansion wave</a>
  <a href="/essential-steinmetz-papers/">Essential papers map</a>
  {authority}
</div>

<div class="source-wave-concepts">{concept_html}</div>

### Why This Is Not Yet A Decoded Source

This work may be historically central, but this archive treats authority registration and decoded source evidence as different states. It becomes a full decoded source only after custody, OCR or text extraction, page mapping, candidate equations, candidate figures, concept and glossary candidates, and review labels are visible.

{WORK_END}"""


def update_work_pages(root: Path, records: list[dict[str, Any]]) -> int:
    works = root / "site" / "src" / "content" / "docs" / "source-library" / "corpus-completion" / "works"
    count = 0
    for record in records:
        path = works / f"{record['work_id']}.mdx"
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        block = work_impact_block(record)
        pattern = re.compile(re.escape(WORK_BEGIN) + r".*?" + re.escape(WORK_END), re.DOTALL)
        if pattern.search(text):
            new_text = pattern.sub(block, text).rstrip() + "\n"
        else:
            marker = "## Current Archive State"
            new_text = text.replace(marker, block + "\n\n" + marker, 1) if marker in text else text.rstrip() + "\n\n" + block + "\n"
        if new_text != text:
            write_text(path, new_text)
            count += 1
    return count


def main() -> None:
    root = Path(__file__).resolve().parents[2]
    matrix = load_json(root / "processed" / "steinmetz_corpus_completion_matrix.json", {"records": []})
    records = wave_records(matrix)
    payload = {
        "generated_at": date.today().isoformat(),
        "quality_note": "Public source-expansion wave. Registered authority targets are not decoded source evidence until custody and review gates are satisfied.",
        "targets": records,
        "concept_impacts": CONCEPT_SOURCE_WAVE,
    }
    write_json(root / "processed" / "steinmetz_source_expansion_wave.json", payload)
    docs = root / "site" / "src" / "content" / "docs"
    write_text(docs / "source-library" / "steinmetz-source-expansion-wave.mdx", build_wave_page(records))
    write_text(docs / "source-library" / "newly-added-steinmetz-works.mdx", build_newly_added_page(matrix))
    write_text(docs / "essential-steinmetz-papers.mdx", build_essential_page(records))
    write_text(docs / "mathematics" / "steinmetz-math-map.mdx", build_math_map_page(records))
    concept_count = update_concepts(root, records)
    work_count = update_work_pages(root, records)
    print(f"Generated Steinmetz source expansion wave: {len(records)} targets, {concept_count} concept pages enriched, {work_count} work records enriched.")


if __name__ == "__main__":
    main()
