#!/usr/bin/env python3
"""Generate public source-text reader pages for processed chapters.

This script turns `processed/*/chapters.json` records into Starlight MDX pages.
The generated pages expose the current OCR/PDF text for every processed
chapter, lecture, section, and report division while preserving candidate
status labels. They are source access pages, not reviewed editions.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
from pathlib import Path
from typing import Any


BASE_URL = ""
GENERATED_NOTE = "{/* Generated by pipeline/scripts/generate_source_text_pages.py. Do not edit by hand. */}"

THEME_LABELS = {
    "alternating-current": "alternating current",
    "complex-quantities": "complex quantities",
    "dielectricity": "dielectricity and capacity",
    "energy-power": "energy and power",
    "ether": "ether references",
    "fields": "field language",
    "hysteresis": "hysteresis",
    "impedance-reactance": "impedance and reactance",
    "magnetism": "magnetism",
    "radiation-light": "radiation and light",
    "transients": "transients",
    "waves-lines": "waves and transmission lines",
}

KEYWORD_TAGS = [
    ("ether", "ether references"),
    ("wave", "waves and transmission lines"),
    ("oscillation", "oscillation"),
    ("impulse", "impulse currents"),
    ("lightning", "lightning and surges"),
    ("surge", "lightning and surges"),
    ("transient", "transient phenomena"),
    ("discharge", "electric discharges"),
    ("magnet", "magnetism"),
    ("hysteresis", "hysteresis"),
    ("reactance", "reactance"),
    ("impedance", "impedance"),
    ("admittance", "admittance"),
    ("conductance", "conductance"),
    ("capacity", "capacity"),
    ("dielectric", "dielectricity"),
    ("alternating", "alternating current"),
    ("symbolic", "symbolic method"),
    ("complex", "complex quantities"),
    ("radiation", "radiation"),
    ("illumination", "illumination"),
]


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def slugify(value: str) -> str:
    value = value.lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = value.strip("-")
    return value or "untitled"


def yaml_quote(value: Any) -> str:
    text = "" if value is None else str(value)
    text = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{text}"'


def html_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def md_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return text.replace("|", "\\|").replace("\n", " ")


def code_fence(text: str) -> str:
    longest = 3
    for match in re.finditer(r"`+", text):
        longest = max(longest, len(match.group(0)) + 1)
    fence = "`" * longest
    return f"{fence}text wrap\n{text.rstrip()}\n{fence}"


def read_source_text(root: Path, record: dict[str, Any]) -> str:
    path = root / str(record.get("text_path") or "")
    if not path.exists():
        return "[Text file missing. Regenerate processed chapter splits before publishing this page.]\n"
    return path.read_text(encoding="utf-8", errors="replace")


def write_source_text_asset(
    root: Path,
    public_data_dir: Path,
    source_id: str,
    record: dict[str, Any],
) -> str:
    text = read_source_text(root, record)
    slug = source_page_slug(record)
    asset_path = public_data_dir / source_id / f"{slug}.txt"
    asset_path.parent.mkdir(parents=True, exist_ok=True)
    asset_path.write_text(text, encoding="utf-8", newline="\n")
    return f"{BASE_URL}/source-texts-data/{source_id}/{slug}.txt"



def github_blob_url(path: Any) -> str:
    repo = "https://github.com/TRUEMODELOFTHEWORLD/Steinmetz-Decoded"
    clean = str(path or "").replace("\\", "/").lstrip("/")
    return f"{repo}/blob/main/{html_escape(clean)}" if clean else repo

def source_page_slug(record: dict[str, Any]) -> str:
    path = Path(str(record.get("text_path") or ""))
    if path.stem:
        return slugify(path.stem)
    return slugify(str(record.get("id") or record.get("title") or "section"))


def source_title_map(catalog: list[dict[str, Any]]) -> dict[str, str]:
    return {str(source["source_id"]): str(source.get("title") or source["source_id"]) for source in catalog}


def source_site_map(catalog: list[dict[str, Any]]) -> dict[str, str]:
    return {str(source["source_id"]): str(source.get("site_path") or "") for source in catalog}


def source_archive_map(catalog: list[dict[str, Any]]) -> dict[str, str]:
    return {
        str(source["source_id"]): str(source.get("internet_archive_id") or "")
        for source in catalog
    }


def source_raw_map(catalog: list[dict[str, Any]]) -> dict[str, str]:
    return {
        str(source["source_id"]): str(source.get("local_raw_file") or "")
        for source in catalog
    }


def chapter_label(record: dict[str, Any]) -> str:
    kind = str(record.get("kind") or "section").replace("-", " ").title()
    number = record.get("number") or record.get("sequence")
    title = str(record.get("title") or "Untitled")
    if number:
        return f"{kind} {number}: {title}"
    return f"{kind}: {title}"


def record_location(record: dict[str, Any]) -> str:
    start = record.get("line_start")
    end = record.get("line_end")
    page_start = record.get("pdf_page_start")
    page_end = record.get("pdf_page_end")
    parts = []
    if page_start and page_end:
        parts.append(f"PDF pages {page_start}-{page_end}" if page_start != page_end else f"PDF page {page_start}")
    if start and end:
        parts.append(f"lines {start}-{end}")
    return ", ".join(parts) or "processed source text"


def status_note(status: str) -> str:
    status_lower = status.lower()
    if "pdf-text" in status_lower:
        return "Embedded PDF text extraction. Verify against page images before exact quotation."
    if "ocr" in status_lower or "candidate" in status_lower:
        return "OCR-derived candidate text. Verify against the scan before exact quotation."
    return "Processed source text. Verify against source custody files before canonical use."


def dedupe(values: list[str], limit: int = 8) -> list[str]:
    seen: set[str] = set()
    output: list[str] = []
    for value in values:
        clean = str(value or "").strip()
        if not clean:
            continue
        key = clean.lower()
        if key in seen:
            continue
        seen.add(key)
        output.append(clean)
        if len(output) >= limit:
            break
    return output


def infer_tags(record: dict[str, Any], source_title: str = "") -> list[str]:
    tags = [str(tag) for tag in record.get("concept_tags") or []]
    tags.extend(THEME_LABELS.get(str(theme), str(theme).replace("-", " ")) for theme in record.get("top_themes") or [])
    haystack = " ".join(
        str(part or "")
        for part in [source_title, record.get("title"), record.get("summary"), " ".join(record.get("top_themes") or [])]
    ).lower()
    for needle, label in KEYWORD_TAGS:
        if needle in haystack:
            tags.append(label)
    return dedupe(tags, 7)


def count_assets_in_record(items: list[dict[str, Any]], record: dict[str, Any]) -> int:
    start = int(record.get("line_start") or 0)
    end = int(record.get("line_end") or 0)
    if not start or not end:
        return 0
    count = 0
    for item in items:
        ref = item.get("source_ref") or {}
        item_start = int(ref.get("line_start") or 0)
        item_end = int(ref.get("line_end") or item_start or 0)
        if item_start and item_end and item_start <= end and item_end >= start:
            count += 1
    return count


def load_source_assets(root: Path, source_id: str) -> dict[str, list[dict[str, Any]]]:
    source_root = root / "processed" / source_id
    equations = load_json(source_root / "equations.json", [])
    figures = load_json(source_root / "figures.json", [])
    return {
        "equations": equations if isinstance(equations, list) else [],
        "figures": figures if isinstance(figures, list) else [],
    }


def section_summary(record: dict[str, Any], source_title: str, tags: list[str]) -> str:
    summary = str(record.get("summary") or "").strip()
    if summary:
        return summary
    title = str(record.get("title") or "this section")
    if tags:
        return (
            f"This section of {source_title} is routed through {', '.join(tags[:4])}. "
            "Read it first for Steinmetz's source language, then use the notes below to decide what requires scan review."
        )
    return (
        f"This section of {source_title} presents Steinmetz's primary text for {title}. "
        "Read the prose as a study layer and verify exact formulas, symbols, and page references against the scan."
    )


def modern_reading_note(source_title: str, tags: list[str]) -> str:
    joined = " ".join(tags).lower()
    title = source_title.lower()
    if "transient" in joined or "impulse" in joined or "surge" in joined or "discharge" in joined:
        return "Read this as an early engineering treatment of non-steady electrical behavior: sudden charge, discharge, wave travel, damping, and surge stress."
    if "impedance" in joined or "reactance" in joined or "admittance" in joined or "alternating current" in joined:
        return "Track how Steinmetz moves between physical circuit behavior and symbolic AC calculation; modern phasor language usually compresses this transition."
    if "magnetism" in joined or "hysteresis" in joined:
        return "Keep magnetic material behavior separate from ideal circuit formulas: Steinmetz often treats lag, loss, saturation, and field action as engineering realities."
    if "radiation" in joined or "illumination" in joined or "light" in joined:
        return "Watch the distinction between radiation as energy in transit and illumination as the practical/physiological result after interaction with matter."
    if "electric circuits" in title:
        return "Read this as circuit theory before many modern textbook conventions were standardized; notation and OCR symbols require especially careful verification."
    return "Use modern terminology as a translation layer, not a replacement for Steinmetz's wording. The original phrasing is part of the evidence."


def build_reader_guide(
    record: dict[str, Any],
    source_title: str,
    source_id: str,
    assets: dict[str, list[dict[str, Any]]],
) -> dict[str, Any]:
    tags = infer_tags(record, source_title)
    equation_count = count_assets_in_record(assets.get("equations", []), record)
    figure_count = count_assets_in_record(assets.get("figures", []), record)
    source_slug = source_page_slug(record)
    formula_map = f"{BASE_URL}/mathematics/equation-atlas/"
    visual_map = f"{BASE_URL}/diagrams/figure-candidate-atlas/"
    workbench = f"{BASE_URL}/chapter-workbench/{source_id}/{source_slug}/"
    return {
        "tags": tags,
        "summary": section_summary(record, source_title, tags),
        "equation_count": equation_count,
        "figure_count": figure_count,
        "modern_note": modern_reading_note(source_title, tags),
        "formula_map": formula_map,
        "visual_map": visual_map,
        "workbench": workbench,
    }


def seo_join(items: list[Any], limit: int = 6) -> str:
    values = []
    for item in items:
        value = str(item or "").strip()
        if value and value not in values:
            values.append(value)
    return ", ".join(values[:limit])


def seo_source_description(source_title: str, records: list[dict[str, Any]]) -> str:
    tags: list[Any] = []
    section_count = len(records)
    for record in records:
        tags.extend(record.get("concept_tags") or [])
    tag_text = seo_join(tags, 7) or "primary source text, equations, diagrams, and electrical engineering concepts"
    return (
        f"Read Charles Proteus Steinmetz's {source_title} as processed source text: "
        f"{section_count} sections with scan-aware OCR/PDF transcripts, concept tags, and routes into {tag_text}."
    )


def seo_reader_description(source_title: str, title: str, location: str, tags: list[Any]) -> str:
    tag_text = seo_join(tags, 6) or "primary source text and electrical engineering history"
    return (
        f"Read {title} from Charles Proteus Steinmetz's {source_title}: "
        f"source text at {location}, with scan verification notes and concept tags for {tag_text}."
    )


def metadata_rows(
    source_title: str,
    record: dict[str, Any],
    location: str,
    text_asset_url: str,
    status: str,
    internet_archive_id: str,
    local_raw_file: str,
) -> str:
    fields = [
        ("Source", source_title),
        ("Section ID", record.get("id") or ""),
        ("Kind", record.get("kind") or ""),
        ("Sequence", record.get("sequence") or ""),
        ("Source Location", location),
        ("Text Path", record.get("text_path") or ""),
        ("Public Text Asset", f'<a href="{html_escape(text_asset_url)}">{html_escape(text_asset_url)}</a>'),
        ("Status", status),
        ("Internet Archive ID", internet_archive_id or "not listed"),
        ("Local Raw File", local_raw_file or "not listed"),
    ]
    rows = []
    for label, value in fields:
        rows.append(f"<tr><th>{html_escape(label)}</th><td>{value if str(value).startswith('<a ') else html_escape(value)}</td></tr>")
    return "\n".join(rows)


def original_scan_block(source_title: str, internet_archive_id: str) -> str:
    if not internet_archive_id:
        return """<div class="source-text-warning" data-layer="source">
  <strong>Original scan:</strong> no Internet Archive scan ID is listed for this source yet. Use the custody files and source manifest until a public scan route is added.
</div>"""
    ia_id = html_escape(internet_archive_id)
    title = html_escape(source_title)
    return f"""<details class="source-reader source-scan-viewer" id="original-scan-viewer" data-layer="source">
  <summary>View Original Scan Inline</summary>
  <p>This embedded Internet Archive scan is the verification layer. Use it when exact wording, page labels, equations, diagrams, or captions matter.</p>
  <iframe src="https://archive.org/embed/{ia_id}" title="Original scan for {title}" loading="lazy"></iframe>
  <p><a href="https://archive.org/details/{ia_id}">Open this scan on Archive.org</a></p>
</details>"""


def build_source_index(
    source_id: str,
    source_title: str,
    source_site_path: str,
    records: list[dict[str, Any]],
    guides: dict[str, dict[str, Any]],
) -> str:
    cards = []
    for record in records:
        slug = source_page_slug(record)
        title = chapter_label(record)
        status = str(record.get("status") or "candidate")
        words = record.get("word_count")
        guide = guides.get(str(record.get("id"))) or {}
        tags = ", ".join(str(tag) for tag in guide.get("tags") or infer_tags(record, source_title)) or "source text"
        equation_count = int(guide.get("equation_count") or 0)
        figure_count = int(guide.get("figure_count") or 0)
        signals = []
        if equation_count:
            signals.append(f"{equation_count} equation/formula candidate{'s' if equation_count != 1 else ''}")
        if figure_count:
            signals.append(f"{figure_count} figure candidate{'s' if figure_count != 1 else ''}")
        signal_text = " - ".join(signals) if signals else "reader-first source section"
        cards.append(
            f"""<a class="source-section-card" href="{BASE_URL}/source-texts/{source_id}/{slug}/">
  <strong>{html_escape(title)}</strong>
  <span>{html_escape(record_location(record))} - {html_escape(record.get('kind') or 'section')} - {words or '-'} words</span>
  <small>{html_escape(tags)} - {html_escape(signal_text)} - {html_escape(status)}</small>
</a>"""
        )
    cards_text = "\n".join(cards)
    first_record = records[0] if records else None
    first_link = (
        f'<a href="{BASE_URL}/source-texts/{source_id}/{source_page_slug(first_record)}/">Start reading first section</a>'
        if first_record
        else ""
    )
    return f"""---
title: {yaml_quote(source_title + " Source Text")}
description: {yaml_quote(seo_source_description(source_title, records))}
pagefind: false
---

{GENERATED_NOTE}

## Choose A Section To Read

Open a section below to read Steinmetz directly. The text is a cleaned candidate reading layer, with scan verification available when exact wording matters.

<div class="source-access-actions">
  {first_link.replace("Start reading first section", "Start reading")}
  <a href="{BASE_URL}{source_site_path}">Open curated source overview</a>
  <a href="{BASE_URL}/chapter-workbench/{source_id}/">Research review workspace</a>
</div>

## Sections

<div class="source-section-grid">
{cards_text}
</div>

<details class="source-reader-notes" data-layer="source">
  <summary>Verification note</summary>
  <p>Use these pages for reading and discovery. Exact quotations, equations, captions, and page labels still need comparison with the original scan.</p>
</details>
"""


def build_reader_page(
    source_id: str,
    source_title: str,
    source_site_path: str,
    record: dict[str, Any],
    text_asset_url: str,
    internet_archive_id: str,
    local_raw_file: str,
    previous_record: dict[str, Any] | None,
    next_record: dict[str, Any] | None,
    guide: dict[str, Any],
) -> str:
    title = chapter_label(record)
    status = str(record.get("status") or "candidate")
    location = record_location(record)
    tags = guide.get("tags") or infer_tags(record, source_title)
    tag_links = " ".join(f"<span>{html_escape(tag)}</span>" for tag in tags) or "<span>untagged</span>"
    reader_tags = "|".join(str(tag) for tag in tags)
    equation_count = int(guide.get("equation_count") or 0)
    figure_count = int(guide.get("figure_count") or 0)
    equation_note = (
        f'{equation_count} equation/formula candidate{"s" if equation_count != 1 else ""} appear in this source range. '
        f'<a href="{html_escape(guide.get("formula_map") or BASE_URL + "/mathematics/equation-atlas/")}">Open the equation atlas</a>.'
        if equation_count
        else "No routed equation candidates are currently attached to this source range."
    )
    figure_note = (
        f'{figure_count} figure candidate{"s" if figure_count != 1 else ""} appear in this source range. '
        f'<a href="{html_escape(guide.get("visual_map") or BASE_URL + "/diagrams/figure-candidate-atlas/")}">Open the visual atlas</a>.'
        if figure_count
        else "No routed figure candidates are currently attached to this source range."
    )
    previous_link = ""
    if previous_record:
        previous_link = (
            f'<a href="{BASE_URL}/source-texts/{source_id}/{source_page_slug(previous_record)}/">'
            f"Previous: {html_escape(chapter_label(previous_record))}</a>"
        )
    next_link = ""
    if next_record:
        next_link = (
            f'<a href="{BASE_URL}/source-texts/{source_id}/{source_page_slug(next_record)}/">'
            f"Next: {html_escape(chapter_label(next_record))}</a>"
        )
    back_link = f'<a href="{BASE_URL}/source-texts/{source_id}/">Back to {html_escape(source_title)} source text</a>'
    nav_links = "\n    ".join(link for link in [previous_link, back_link, next_link] if link)
    scan_link = (
        f'<a href="#original-scan-viewer">Original scan</a>'
        if internet_archive_id
        else '<span>No public scan listed yet</span>'
    )
    archive_note = (
        f'<a href="https://archive.org/details/{html_escape(internet_archive_id)}">Archive.org scan</a>'
        if internet_archive_id
        else '<span>No Archive.org scan listed yet</span>'
    )
    github_link = github_blob_url(record.get("text_path") or "")
    review_url = f"{BASE_URL}/chapter-workbench/{source_id}/{source_page_slug(record)}/"

    return f"""---
title: {yaml_quote(title)}
description: {yaml_quote(seo_reader_description(source_title, title, location, tags))}
pagefind: false
---

{GENERATED_NOTE}

<section class="source-reading-desk" id="source-text" data-layer="source">
  <div class="source-reader-hero-panel">
    <p class="source-reader-eyebrow">Primary Source Reader</p>
    <h2>{html_escape(title)}</h2>
    <p>{html_escape(source_title)} - {html_escape(location)}</p>
    <div class="source-reader-status-row">
      <span>{html_escape(status)}</span>
      <span>scan verification required for exact quotation</span>
    </div>
    <nav class="source-reader-actions" aria-label="Source reader actions">
      {scan_link}
      <a href="{BASE_URL}/source-texts/{source_id}/">Source index</a>
      <a href="{BASE_URL}/chapter-workbench/{source_id}/{source_page_slug(record)}/#chapter-local-concept-hits">Research review</a>
    </nav>
  </div>

  <section class="source-reader-guide" aria-label="Reading guide">
    <div>
      <span>What this section is about</span>
      <p>{html_escape(guide.get("summary") or section_summary(record, source_title, tags))}</p>
    </div>
    <div>
      <span>Key concepts to watch</span>
      <p>{html_escape(", ".join(tags) if tags else "source language, notation, and scan verification")}</p>
    </div>
    <div>
      <span>Where equations and figures occur</span>
      <p>{equation_note} {figure_note}</p>
    </div>
    <div>
      <span>Modern reading note</span>
      <p>{html_escape(guide.get("modern_note") or modern_reading_note(source_title, tags))}</p>
    </div>
    <div>
      <span>Verification note</span>
      <p>Readable text is for study. Exact equations, symbols, captions, and page labels require scan verification; formula-like OCR fragments are isolated in the reader instead of treated as reviewed prose.</p>
    </div>
  </section>

  <div
    class="source-text-loader source-text-manuscript"
    id="source-text-reader"
    data-source-text-url="{html_escape(text_asset_url)}"
    data-reader-title="{html_escape(title)}"
    data-reader-source="{html_escape(source_title)}"
    data-reader-location="{html_escape(location)}"
    data-reader-status="{html_escape(status)}"
    data-reader-tags="{html_escape(reader_tags)}"
    data-reader-review-url="{html_escape(review_url)}"
  >Loading source text...</div>
</section>

<details class="source-reader-notes" data-layer="source">
  <summary>Verification notes and tags</summary>
  <p>This reader is optimized for study and discovery. Treat the text as a candidate reading layer until exact wording, equations, captions, and page labels are checked against the original scan.</p>
  <p>{html_escape(status_note(status))}</p>
  <p class="source-reader-secondary-links"><a href="{BASE_URL}{source_site_path}">Source overview</a> {archive_note} <a href="{github_link}">Text file on GitHub</a></p>
  <div class="source-text-tags" data-layer="source">
    {tag_links}
  </div>
  <p><a href="{html_escape(text_asset_url)}">Open the plain text asset</a></p>
</details>

<noscript>
  <p><a href="{html_escape(text_asset_url)}">Open the source text asset</a></p>
</noscript>

## Original Scan

{original_scan_block(source_title, internet_archive_id)}

<details class="source-metadata-panel" id="reader-metadata" data-layer="source">
  <summary>Reader Metadata And Custody Notes</summary>
  <table class="codex-status-table source-metadata-table">
    <tbody>
{metadata_rows(source_title, record, location, text_asset_url, status, internet_archive_id, local_raw_file)}
    </tbody>
  </table>
</details>

<nav class="source-page-navigation" data-layer="source" aria-label="Source text navigation">
  <strong>Continue Reading</strong>
  <div class="source-text-toolbar">
    {nav_links}
  </div>
</nav>
"""

def build_root_index(catalog: list[dict[str, Any]], grouped: dict[str, list[dict[str, Any]]]) -> str:
    cards = []
    total_sections = 0
    for source in catalog:
        source_id = str(source["source_id"])
        records = grouped.get(source_id, [])
        total_sections += len(records)
        if not records:
            continue
        cards.append(
            f"""<a class="source-section-card source-book-card" href="{BASE_URL}/source-texts/{source_id}/">
  <strong>{html_escape(source.get('title') or source_id)}</strong>
  <span>{len(records)} processed text sections - {html_escape(source.get('year') or '')}</span>
  <small>{html_escape(source.get('processed_status') or '')}</small>
</a>"""
        )
    cards_text = "\n".join(cards)
    return f"""---
title: Source Text Browser
description: Generated public reader for every processed Steinmetz chapter, lecture, section, and report division.
pagefind: false
---

{GENERATED_NOTE}

The source text browser is the archive's broad reading layer. Choose a book, then choose a section, and the site opens directly into the reader.

<div class="source-access source-reader-hero">
  <div>
    <strong>{total_sections} processed source sections</strong>
    <p>Use this page when you want Steinmetz's text first, before commentary, dashboards, or research workbenches.</p>
  </div>
</div>

## Source Indexes

<div class="source-section-grid">
{cards_text}
</div>

<details class="source-reader-notes" data-layer="source">
  <summary>How to use this browser</summary>

1. Open a source index.
2. Read the generated text page for a chapter or section.
3. Follow concept tags into curated pages when available.
4. Treat OCR/PDF text as candidate material until scan verification is complete.
5. Promote important passages into concept, equation, diagram, glossary, comparison, or hidden-gem pages only after checking the source image.
</details>
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("site") / "src" / "content" / "docs" / "source-texts",
    )
    args = parser.parse_args()

    root = args.root.resolve()
    out_dir = root / args.out
    public_data_dir = root / "site" / "public" / "source-texts-data"
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    if public_data_dir.exists():
        shutil.rmtree(public_data_dir)
    public_data_dir.mkdir(parents=True, exist_ok=True)

    catalog = load_json(root / "sources" / "source_catalog.json", [])
    titles = source_title_map(catalog)
    site_paths = source_site_map(catalog)
    archive_ids = source_archive_map(catalog)
    raw_files = source_raw_map(catalog)
    atlas = load_json(root / "processed" / "chapter_atlas.json", {})
    atlas_records = {
        str(record.get("id")): record
        for record in atlas.get("records", [])
        if isinstance(record, dict)
    }

    grouped: dict[str, list[dict[str, Any]]] = {}
    for source in catalog:
        source_id = str(source["source_id"])
        chapters = load_json(root / "processed" / source_id / "chapters.json", [])
        if not isinstance(chapters, list):
            chapters = []
        for chapter in chapters:
            atlas_record = atlas_records.get(str(chapter.get("id")), {})
            merged = dict(chapter)
            if atlas_record:
                merged["word_count"] = atlas_record.get("word_count")
                merged["theme_counts"] = atlas_record.get("theme_counts")
                merged["top_themes"] = atlas_record.get("top_themes")
            grouped.setdefault(source_id, []).append(merged)

    write_text(out_dir / "index.mdx", build_root_index(catalog, grouped))

    total_pages = 1
    for source_id, records in grouped.items():
        if not records:
            continue
        records.sort(key=lambda record: int(record.get("sequence") or 0))
        source_title = titles.get(source_id, source_id)
        source_site_path = site_paths.get(source_id, f"/sources/{source_id}/")
        internet_archive_id = archive_ids.get(source_id, "")
        local_raw_file = raw_files.get(source_id, "")
        assets = load_source_assets(root, source_id)
        guides = {
            str(record.get("id")): build_reader_guide(record, source_title, source_id, assets)
            for record in records
        }
        source_dir = out_dir / source_id
        write_text(source_dir / "index.mdx", build_source_index(source_id, source_title, source_site_path, records, guides))
        total_pages += 1
        for index, record in enumerate(records):
            previous_record = records[index - 1] if index else None
            next_record = records[index + 1] if index + 1 < len(records) else None
            text_asset_url = write_source_text_asset(root, public_data_dir, source_id, record)
            write_text(
                source_dir / f"{source_page_slug(record)}.mdx",
                build_reader_page(
                    source_id,
                    source_title,
                    source_site_path,
                    record,
                    text_asset_url,
                    internet_archive_id,
                    local_raw_file,
                    previous_record,
                    next_record,
                    guides.get(str(record.get("id"))) or {},
                ),
            )
            total_pages += 1

    print(f"Generated {total_pages} source-text pages in {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
