#!/usr/bin/env python3
"""Generate a public-reader quality audit for high-risk site surfaces."""

from __future__ import annotations

import json
import re
from datetime import date
from pathlib import Path


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def rel(root: Path, path: Path) -> str:
    return path.relative_to(root).as_posix()


def scan(root: Path) -> dict[str, object]:
    docs = root / "site" / "src" / "content" / "docs"
    findings: list[dict[str, str]] = []

    for path in (docs / "mathematics" / "equation-atlas").glob("**/*.mdx"):
        text = path.read_text(encoding="utf-8")
        if "equation-render" in text:
            findings.append(
                {
                    "severity": "high",
                    "surface": rel(root, path),
                    "issue": "Equation atlas contains rendered math spans.",
                    "fix": "Keep raw OCR candidates as verification cards until scan-reviewed.",
                }
            )
        if "OCR formula candidate" not in text and "equation-candidate-card" in text:
            findings.append(
                {
                    "severity": "medium",
                    "surface": rel(root, path),
                    "issue": "Equation candidate cards are missing explicit OCR-candidate language.",
                    "fix": "Regenerate with generate_equation_atlas.py.",
                }
            )

    for path in (docs / "sources").glob("*/index.mdx"):
        text = path.read_text(encoding="utf-8")
        if re.search(r"^## Candidate Processing State", text, flags=re.MULTILINE):
            findings.append(
                {
                    "severity": "medium",
                    "surface": rel(root, path),
                    "issue": "Source page exposes candidate processing state as a normal reader section.",
                    "fix": "Wrap it in a research-metadata details block or regenerate the source page.",
                }
            )
        if "BEGIN GENERATED SOURCE RESEARCH DASHBOARD" in text and "source-research-dashboard" not in text:
            findings.append(
                {
                    "severity": "medium",
                    "surface": rel(root, path),
                    "issue": "Generated source dashboard is not collapsed as research metadata.",
                    "fix": "Regenerate with generate_source_research_dashboards.py.",
                }
            )

    for path in [docs / "concepts" / "index.mdx", docs / "index.mdx", docs / "start-reading.mdx"]:
        if not path.exists():
            findings.append(
                {
                    "severity": "high",
                    "surface": rel(root, path),
                    "issue": "Primary public entry page is missing.",
                    "fix": "Restore the reader-first public entry page.",
                }
            )

    counts: dict[str, int] = {}
    for finding in findings:
        counts[finding["severity"]] = counts.get(finding["severity"], 0) + 1

    return {
        "generated_at": date.today().isoformat(),
        "quality_note": "This audit checks reader-facing trust and usability risks. It does not replace human source review.",
        "finding_count": len(findings),
        "severity_counts": counts,
        "findings": findings,
    }


def build_page(audit: dict[str, object]) -> str:
    findings = audit.get("findings", [])
    rows = []
    for finding in findings:
        rows.append(
            "<tr>"
            f"<td>{finding['severity']}</td>"
            f"<td><code>{finding['surface']}</code></td>"
            f"<td>{finding['issue']}</td>"
            f"<td>{finding['fix']}</td>"
            "</tr>"
        )
    if not rows:
        rows.append("<tr><td colspan=\"4\">No high-risk reader regressions detected by this audit.</td></tr>")

    return f"""---
title: Public Reader Quality Audit
description: Generated guardrail for public-reader trust, math rendering safety, and source-page usability.
---

{{/* Generated by pipeline/scripts/generate_public_reader_quality_audit.py. Do not edit by hand. */}}

This page protects the public reader experience. It checks for recurring risks: raw OCR equation candidates rendered as polished math, source pages that expose processing metadata too early, and missing public entry pages.

<div class="codex-signal">
  <div><strong>{audit.get('finding_count')}</strong><p>active findings</p></div>
  <div><strong>{audit.get('severity_counts', {}).get('high', 0)}</strong><p>high severity</p></div>
  <div><strong>{audit.get('severity_counts', {}).get('medium', 0)}</strong><p>medium severity</p></div>
</div>

## Findings

<table class="codex-status-table">
  <thead>
    <tr><th>Severity</th><th>Surface</th><th>Issue</th><th>Fix</th></tr>
  </thead>
  <tbody>
{chr(10).join(rows)}
  </tbody>
</table>

## Reader Standard

1. Public entry pages should tell readers where to begin.
2. Source readers should show Steinmetz text before research machinery.
3. Raw OCR formulas should never be dressed up as verified math.
4. Research dashboards should remain available but visually secondary.
5. Mobile readers should receive the same clear reading path as desktop readers.
"""


def main() -> int:
    root = Path.cwd()
    audit = scan(root)
    write_json(root / "processed" / "public_reader_quality_audit.json", audit)
    write_json(root / "site" / "public" / "data" / "public_reader_quality_audit.json", audit)
    write_text(root / "site" / "src" / "content" / "docs" / "roadmap" / "public-reader-quality-audit.mdx", build_page(audit))
    print(f"Generated public reader quality audit with {audit['finding_count']} findings.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
